application: gcdc2013-helios
version: dev
runtime: python27
api_version: 1
threadsafe: yes

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$
- ^(.*/)?test$
- ^test/(.*/)?
- ^COPYING.LESSER
- ^README\..*
- \.gitignore
- ^\.git/.*
- \.*\.lint$
- ^fabfile\.py
- ^testrunner\.py
- ^Gruntfile\.js
- ^node_modules/(.*/)?
- ^(.*)\.scss$

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

# Runs the storage script to download new data and store it with NDB
- url: /_storeit(.*)
  script: kepler.storage.app

# Serves the data as a RESTful API
- url: /api/(.*)
  script: kepler.api.app

# Everything else is served through the Single Page Application
- url: .*
  static_files: index.html
  upload: index.html

libraries:
- name: webapp2
  version: "2.5.2"

# cron:
# - description: minutely oh shit test
#   url: /api/test
#   schedule: every 1 minutes