# This data will have to be hand-curated, as there is no data-source
# Should also include our own solar system
systems = {
  # "Solar": {
  #   "distance": 0.000001,
  #   "num_stars": 1,
  #   "num_planets": 8,
  #   "period": 0.0,
  #   "semimajor_axis": 0.0,
  #   "semimajor_axis": 0.0,
  # },
  "Kepler-16(AB)": {
    "distance": 60.0,
    "num_stars": 2,
    "num_planets": 1,
    "period": 41.07922,
    "semimajor_axis": 0.22431,
    "habzone_max": 0.795,
    "habzone_min": 0.304,
    "ra": 19.2717,
    "dec": 51.7575,
    "inclination": 0,
    "eccentricity": 0.15944,
    "planets": [],
    "stars": [
      {
        "name": "Kepler-16A",
        "distance": 60.0,
        "metallicity": -0.3,
        "luminosity": 0.148647,
        "age": 0.0,
        "hip_name": "",
        "hd_name": "",
        "size_from_planet": 0.4915,
        "mag_from_planet": -25.4,
        "constellation": "Cyg",
        "magnitude": 12.0,
        "radius": 0.6489,
        "mass": 0.6897,
        "temperature": 4450.0,
        "type": "K"
      },
      {
        "name": "Kepler-16B",
        "distance": 60.0,
        "metallicity": 0.0,
        "luminosity": 0.0,
        "age": 0.0,
        "hip_name": "",
        "hd_name": "",
        "size_from_planet": 0.0,
        "mag_from_planet": 0.0,
        "constellation": "Cyg",
        "magnitude": 0.0,
        "radius": 0.22623,
        "mass": 0.20255,
        "temperature": 3750.0,
        "type": "M"
      }
    ]
  },
  "PSR B1620-26": {
    "distance": 3800.0,
    "num_stars": 2,
    "num_planets": 1,
    "period": 191.0,
    "semimajor_axis": 0.0,
    "habzone_max": 7.054,
    "habzone_min": 2.862,
    "ra": 16.3939,
    "dec": -26.5314,
    "inclination": 0,
    "eccentricity": 0.0,
    "planets": [],
    "stars": [
      {
        "name": "PSR B1620-26A",
        "metallicity": 0.0,
        "type": "Pulsar",
        "luminosity": 14.459006,
        "age": 0.0,
        "temperature": 5700.0,
        "hd_name": "",
        "hip_name": "",
        "size_from_planet": 0.0,
        "mag_from_planet": -22.8,
        "mass": 1.95,
        "radius": 0.0,
        "constellation": "Sco",
        "magnitude": 24.0
      },
      {
        "name": "PSR B1620-26B",
        "metallicity": 0.0,
        "magnitude": 0.0,
        "type": "White Dwarf",
        "luminosity": 0.0,
        "age": 13,
        "temperature": 10000.0,
        "hd_name": "",
        "hip_name": "",
        "size_from_planet": 0.0,
        "mag_from_planet": 0.0,
        "mass": 0.34,
        "radius": 0.017,
        "constellation": "Sco"
      },
    ]
  },
  "DP Leo": {
    "distance": 400.0,
    "num_stars": 2,
    "num_planets": 1,
    "semimajor_axis": 0.0027,
    "period": 0.07,
    "habzone_max": 0.794,
    "habzone_min": 0.34,
    "ra": 11.2878,
    "dec": 17.9614,
    "inclination": 0,
    "eccentricity": 0.0,
    "planets": [],
    "stars": [
      {
        "name": "DP Leo A",
        "distance": 400.0,
        "mass": 0.69,
        "radius": 0.0114,
        "type": "Pulsar",
        "temperature": 9790.0,
        "hd_name": "",
        "hip_name": "",
        "size_from_planet": 0.0118,
        "mag_from_planet": -20.7,
        "constellation": "Leo",
        "metallicity": 0.0,
        "age": 0.0,
        "magnitude": 17.5,
        "luminosity": 0.226671
      },
      {
        "name": "DP Leo B",
        "distance": 400.0,
        "mass": 0.09,
        "radius": 0.12,
        "type": "M5V",
        "temperature": 3000.0,
        "hd_name": "",
        "hip_name": "",
        "size_from_planet": 0.0,
        "mag_from_planet": 0.0,
        "constellation": "Leo",
        "metallicity": 0.0,
        "age": 0.0,
        "magnitude": 0.0,
        "luminosity": 0.00105
      }
    ]
  },
  "NN Ser(AB)": {
    "distance": 500.0,
    "num_stars": 2,
    "num_planets": 2,
    "semimajor_axis": 0.00397884,
    "period": 0.000356,
    "habzone_max": 0.774,
    "habzone_min": 0.314,
    "ra": 15.8822,
    "dec": 12.9131,
    "inclination": 89.6,
    "eccentricity": 0.0,
    "planets": [],
    "stars": [
      {
        "distance": 500.0,
        "name": "NN Ser A",
        "hd_name": "",
        "hip_name": "",
        "mass": 0.65,
        "radius": 0.0211,
        "type": "White Dwarf",
        "temperature": 57000.0,
        "size_from_planet": 0.0,
        "mag_from_planet": -21.2,
        "constellation": "Ser",
        "metallicity": 0.0,
        "age": 0.0,
        "magnitude": 16.6,
        "luminosity": 4.2
      },
      {
        "name": "NN Ser B",
        "distance": 500.0,
        "mass": 0.111,
        "radius": 0.154,
        "type": "M4V",
        "temperature": 3000.0,
        "hd_name": "",
        "hip_name": "",
        "size_from_planet": 0.0,
        "mag_from_planet": 0.0,
        "constellation": "Ser",
        "metallicity": 0.0,
        "age": 0.0,
        "magnitude": 16.6,
        "luminosity": 0.00172
      }
    ]
  },
  # Red Dwarf and a Brown Dwarf
  # "Ross 458(AB)": {
  #   "distance": 114.0,
  #   "num_stars": 2,
  #   "num_planets": 1,
  #   "period": 41.07922,
  #   "semimajor_axis": 0.22431,
  #   "habzone_max": 4.271,
  #   "habzone_min": 1.591,
  #   "ra": 13.0131,
  #   "dec": 12.3758,
  #   "inclination": 0,
  #   "eccentricity": 0.15944,
  #   "planets": [],
  #   "stars": [
  #     {
  #       "name": "Kepler-16A",
  #       "distance": 60.0,
  #       "metallicity": -0.3,
  #       "luminosity": 0.148647,
  #       "age": 0.0,
  #       "hip_name": "",
  #       "hd_name": "",
  #       "size_from_planet": 0.4915,
  #       "mag_from_planet": -25.4,
  #       "constellation": "Cyg",
  #       "magnitude": 12.0,
  #       "radius": 0.6489,
  #       "mass": 0.6897,
  #       "temperature": 4450.0,
  #       "type": "K"
  #     },
  #     {
  #       "name": "Kepler-16B",
  #       "distance": 60.0,
  #       "metallicity": 0.0,
  #       "luminosity": 0.0,
  #       "age": 0.0,
  #       "hip_name": "",
  #       "hd_name": "",
  #       "size_from_planet": 0.0,
  #       "mag_from_planet": 0.0,
  #       "constellation": "Cyg",
  #       "magnitude": 0.0,
  #       "radius": 0.22623,
  #       "mass": 0.20255,
  #       "temperature": 3750.0,
  #       "type": "M"
  #     }
  #   ]
  # },
}